# Generated by Django 5.2.6 on 2025-10-24 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('gratis', 'Gratis'), ('basico', 'Básico'), ('premium', 'Premium')], help_text='Plan adquirido', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Fecha de inicio del plan')),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha de expiración del plan')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado en Bs.', max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, help_text='Método de pago utilizado (QR, Tarjeta, etc.)', max_length=50, null=True)),
                ('referencia_pago', models.CharField(blank=True, help_text='ID de transacción o referencia de pago', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si esta suscripción está activa')),
                ('cancelado', models.BooleanField(default=False, help_text='Si fue cancelado manualmente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Suscripción',
                'verbose_name_plural': 'Historial de Suscripciones',
                'db_table': 'historial_suscripciones',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['usuario', '-fecha_inicio'], name='historial_s_usuario_357604_idx'), models.Index(fields=['activo'], name='historial_s_activo_0bf566_idx')],
            },
        ),
    ]
