# Generated by Django 5.2.6 on 2025-09-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
