# Generated by Django 5.2.6 on 2025-10-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_alertas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
