# Generated by Django 5.2.6 on 2025-10-12 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_alertas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertas',
            name='fecha',
            field=models.DateField(),
        ),
    ]
