# Generated by Django 5.2.6 on 2025-10-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alertas_created_at_alter_alertas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
