# Generated by Django 5.2.6 on 2025-10-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_alertas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_expiracion_plan',
            field=models.DateTimeField(blank=True, help_text='Fecha en que expira el plan actual', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='minutos_usados_hoy',
            field=models.IntegerField(default=0, help_text='Minutos de entrenamiento usados hoy'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan_actual',
            field=models.CharField(choices=[('gratis', 'Gratis'), ('basico', 'Básico'), ('premium', 'Premium')], default='gratis', help_text='Plan de suscripción actual', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_sesion',
            field=models.DateField(blank=True, help_text='Última fecha de entrenamiento', null=True),
        ),
    ]
