# Generated by Django 5.2.6 on 2025-10-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoseTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(help_text='Tipo de ejercicio (flexion, sentadilla, etc.)', max_length=50)),
                ('landmarks', models.JSONField(help_text='Array de puntos clave detectados por BlazePose')),
                ('angulos', models.JSONField(help_text='Diccionario de ángulos calculados (codo, rodilla, espalda, etc.)')),
                ('etiqueta', models.CharField(choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], help_text='Etiqueta de la postura', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dato de Entrenamiento de Pose',
                'verbose_name_plural': 'Datos de Entrenamiento de Poses',
                'db_table': 'pose_training_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
