# Generated by Django 5.2.6 on 2025-10-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posetrainingdata',
            name='duracion_segundos',
            field=models.FloatField(blank=True, help_text='Duración total de la secuencia en segundos', null=True),
        ),
        migrations.AddField(
            model_name='posetrainingdata',
            name='fps',
            field=models.FloatField(blank=True, help_text='Frames por segundo de la grabación', null=True),
        ),
        migrations.AddField(
            model_name='posetrainingdata',
            name='frames',
            field=models.JSONField(blank=True, help_text='Array de frames con landmarks y ángulos a lo largo del tiempo', null=True),
        ),
        migrations.AddField(
            model_name='posetrainingdata',
            name='tipo',
            field=models.CharField(choices=[('snapshot', 'Snapshot'), ('secuencia', 'Secuencia')], default='snapshot', help_text='Tipo de dato: snapshot individual o secuencia continua', max_length=20),
        ),
        migrations.AddField(
            model_name='posetrainingdata',
            name='total_frames',
            field=models.IntegerField(blank=True, help_text='Número total de frames en la secuencia', null=True),
        ),
        migrations.AlterField(
            model_name='posetrainingdata',
            name='angulos',
            field=models.JSONField(blank=True, help_text='Diccionario de ángulos calculados (solo para snapshots)', null=True),
        ),
        migrations.AlterField(
            model_name='posetrainingdata',
            name='etiqueta',
            field=models.CharField(choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], help_text='Etiqueta de la postura/movimiento', max_length=20),
        ),
        migrations.AlterField(
            model_name='posetrainingdata',
            name='landmarks',
            field=models.JSONField(blank=True, help_text='Array de puntos clave detectados por BlazePose (solo para snapshots)', null=True),
        ),
        migrations.AddIndex(
            model_name='posetrainingdata',
            index=models.Index(fields=['ejercicio', 'tipo', 'etiqueta'], name='pose_traini_ejercic_2b521e_idx'),
        ),
        migrations.AddIndex(
            model_name='posetrainingdata',
            index=models.Index(fields=['tipo'], name='pose_traini_tipo_9bfa04_idx'),
        ),
    ]
