# Generated by Django 5.2 on 2025-11-21 05:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenamientos_semanales', models.IntegerField(default=0)),
                ('minutos_totales_semana', models.IntegerField(default=0)),
                ('calorias_quemadas_semana', models.IntegerField(default=0)),
                ('racha_dias', models.IntegerField(default=0)),
                ('ultima_actualizacion_racha', models.DateField(blank=True, null=True)),
                ('datos_grafica_semanal', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadísticas de Usuario',
                'verbose_name_plural': 'Estadísticas de Usuarios',
                'db_table': 'estadisticas_usuario',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('objetivo', models.CharField(choices=[('fuerza', 'Fuerza'), ('hipertrofia', 'Hipertrofia'), ('perdida_peso', 'Pérdida de Peso'), ('resistencia', 'Resistencia'), ('movilidad', 'Movilidad'), ('rehabilitacion', 'Rehabilitación')], default='fuerza', max_length=50)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='intermedio', max_length=20)),
                ('categoria', models.CharField(choices=[('gimnasio', 'Gimnasio'), ('fisioterapia', 'Fisioterapia')], default='gimnasio', max_length=20)),
                ('parte_cuerpo', models.CharField(default='cuerpo completo', max_length=100)),
                ('dias_por_semana', models.IntegerField(default=3)),
                ('duracion_minutos', models.IntegerField(default=45)),
                ('progreso', models.IntegerField(default=0)),
                ('datos_rutina', models.JSONField(blank=True, null=True)),
                ('generada_por_ia', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'db_table': 'rutinas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(default=0)),
                ('calorias_quemadas', models.IntegerField(default=0)),
                ('ejercicios_completados', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('datos_sesion', models.JSONField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='rutinas.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
                'db_table': 'sesiones_entrenamiento',
                'ordering': ['-fecha'],
            },
        ),
    ]
